# Generated by Django 4.2.6 on 2024-01-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_subscription_comment_alter_subscription_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='comment',
            field=models.CharField(max_length=50),
        ),
    ]
